version: '3.8'

services:
  libreoffice-online:
    image: libreoffice/online:master
    container_name: libreoffice-online
    ports:
      - "9980:9980"
    environment:
      - domain=localhost:3001|localhost:3000|localhost:7069
      - username=admin
      - password=admin
      - DONT_GEN_SSL_CERT=1
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:net.frame_ancestors=localhost:* --o:storage.wopi.host[0]=localhost:7069
    cap_add:
      - MKNOD
    tty: true
    restart: unless-stopped
    networks:
      - libreoffice-net

networks:
  libreoffice-net:
    driver: bridge
